name: Back Inside The Box - Media
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b1b1b1'
    - '#747474'
    - '#2c2c2c'
    - '#e3e3e3'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
